# Generated by Django 2.1.7 on 2019-08-16 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20190815_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='answer',
            field=models.PositiveIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='credit',
            field=models.PositiveIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='question',
            field=models.PositiveIntegerField(blank=True),
        ),
    ]
