# Generated by Django 2.1.7 on 2019-08-17 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20190816_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='answer',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='credit',
            field=models.PositiveIntegerField(blank=True, default=1000),
        ),
        migrations.AlterField(
            model_name='profile',
            name='question',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
