# Generated by Django 2.1.7 on 2019-08-16 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_auto_20190815_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='photo',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
