# Generated by Django 2.1.7 on 2019-08-16 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0003_auto_20190816_1045'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='credit',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
