# Generated by Django 2.1.7 on 2019-08-16 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0004_post_credit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='credit',
            field=models.PositiveIntegerField(blank=True),
        ),
    ]
