# Generated by Django 2.1.7 on 2019-08-16 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0005_auto_20190816_1500'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='participant',
            field=models.PositiveIntegerField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
