# Generated by Django 2.1.7 on 2019-08-16 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0006_post_participant'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='max_participant',
            field=models.PositiveIntegerField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
