# Generated by Django 2.1.7 on 2019-08-17 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0011_withdraw'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdraw',
            name='done',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
