# Generated by Django 2.1.7 on 2019-08-17 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0013_deposit'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposit',
            name='credit_wait',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='withdraw',
            name='credit_wait',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
