# Generated by Django 2.1.7 on 2019-08-20 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0017_auto_20190820_1451'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment2',
            name='done',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
