# Generated by Django 2.1.7 on 2019-08-20 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0018_comment2_done'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment2',
            name='done',
            field=models.BooleanField(default=False),
        ),
    ]
