# Generated by Django 2.1.7 on 2019-08-20 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0019_auto_20190820_1505'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment2',
            name='photo',
            field=models.ImageField(default='123.png', upload_to=''),
            preserve_default=False,
        ),
    ]
