# Generated by Django 2.1.7 on 2019-08-22 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0023_auto_20190822_1839'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='total_credit',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
