# Generated by Django 2.1.7 on 2019-08-22 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0024_post_total_credit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='total_credit',
        ),
    ]
